In [3]:
import pandas as pd
import requests

# --------------------------------------------------
# 1. CSV DATA
# --------------------------------------------------

df_csv = pd.DataFrame({
    "Country": ["India", "USA", "China", "Japan", "Germany"],
    "GDP": [3900, 30500, 19400, 4300, 4900],
    "Population": [1450, 340, 1410, 123, 84]
})

df_csv.to_csv("/content/sample.csv", index=False)

df_csv = pd.read_csv("/content/sample.csv")

print("CSV File Head:")
display(df_csv.head())


# --------------------------------------------------
# 2. EXCEL DATA
# --------------------------------------------------

df_excel = pd.DataFrame({
    "Year": [2020, 2021, 2022, 2023, 2024],
    "Investment": [120, 150, 180, 220, 260],
    "Projects": [10, 14, 18, 23, 28]
})

df_excel.to_excel("/content/sample.xlsx", index=False)

df_excel = pd.read_excel("/content/sample.xlsx")

print("Excel File Head:")
display(df_excel.head())


# --------------------------------------------------
# 3. WEB DATA
# --------------------------------------------------

url = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

tables = pd.read_html(response.text)

df_web = tables[0]

print("Wikipedia GDP Table Head:")
display(df_web.head())


# --------------------------------------------------
# 4. EXPORT EXCEL DATA
# --------------------------------------------------

df_excel.to_excel("/content/output.xlsx", index=False)

print("Exported Excel Data Head:")
display(df_excel.head())

CSV File Head:

   Country    GDP  Population
0    India   3900        1450
1      USA  30500         340
2    China  19400        1410
3    Japan   4300         123
4  Germany   4900          84

Excel File Head:

   Year  Investment  Projects
0  2020         120        10
1  2021         150        14
2  2022         180        18
3  2023         220        23
4  2024         260        28

Wikipedia GDP Table Head:

/tmp/ipykernel_945/3853575880.py:52: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

                                                   0
0  Largest economies in the world by nominal GDP ...

Exported Excel Data Head:

   Year  Investment  Projects
0  2020         120        10
1  2021         150        14
2  2022         180        18
3  2023         220        23
4  2024         260        28